paypal:
  client-id: ${PAYPAL_CLIENT_KEY}
  client-secret: ${PAYPAL_SECRET_KEY}
  mode : sandbox

stripe:
  api-key: ${STRIPE_SECRET_KEY}
  webhook:
    secret:  ${STRIPE_WEBHOOK_KEY}

adyen:
  api-key: ${ADYEN_SECRET_KEY}
  client-key: ${ADYEN_CLIENT_KEY}
  environment: test
  merchant-account: IttovativeECOM
  endpoint: https://checkout-test.adyen.com/v68/payments
  return-url: http://localhost:8080/api/v1/handle-redirect
  hmac-key:  ${ADYEN_HMAC_KEY}